ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "symptoms" TEXT;
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "contributingFactors" JSONB;
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "fiveWhys" JSONB;
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "isKnownError" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "kbArticleId" TEXT;

ALTER TABLE "Approval" ADD COLUMN IF NOT EXISTS "approverRole" TEXT NOT NULL DEFAULT 'TECH_APPROVER';

ALTER TABLE "ChangeRequest" ADD COLUMN IF NOT EXISTS "pirSuccess" BOOLEAN;
ALTER TABLE "ChangeRequest" ADD COLUMN IF NOT EXISTS "actualDuration" INTEGER;
ALTER TABLE "ChangeRequest" ADD COLUMN IF NOT EXISTS "pirIssues" TEXT;
ALTER TABLE "ChangeRequest" ADD COLUMN IF NOT EXISTS "lessonsLearned" TEXT;
