import {NextRequest,NextResponse} from 'next/server';
import {z} from 'zod';
import {prisma} from '@/lib/prisma';
import {requireUser} from '@/lib/session';
import {sanitizeHtml} from '@/lib/sanitize';
import {structuredError} from '@/lib/api-errors';
import {calculateRisk,detectFreezePeriod,initialStatusForType} from '@/lib/change-workflow';
import {demoChangeRecords,isLocalDemo} from '@/lib/demo-data';

const clean=(x:string)=>sanitizeHtml(x);
const approver=z.object({approverId:z.string(),approverRole:z.enum(['CAB_CHAIR','TECH_APPROVER','BUSINESS_APPROVER'])});
const schema=z.object({title:z.string().min(4),description:z.string().min(10).transform(clean),type:z.enum(['STANDARD','NORMAL','EMERGENCY']),risk:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']).optional(),implementationPlan:z.string().min(10).transform(clean),rollbackPlan:z.string().optional().default('').transform(clean),windowStart:z.coerce.date().nullable().optional(),windowEnd:z.coerce.date().nullable().optional(),approvers:z.array(approver).default([])});
export async function GET(req:NextRequest){try{if(isLocalDemo())return NextResponse.json({changes:demoChangeRecords,total:demoChangeRecords.length,page:1,totalPages:1});let u=await requireUser('change:manage'),q=req.nextUrl.searchParams,page=Math.max(1,+(q.get('page')||1)),limit=Math.min(60,Math.max(1,+(q.get('limit')||24))),where:any={tenantId:u.tenantId};if(q.get('status'))where.status=q.get('status');let[changes,total]=await prisma.$transaction([prisma.changeRequest.findMany({where,include:{requester:{select:{name:true}},approvals:true},orderBy:{createdAt:'desc'},skip:(page-1)*limit,take:limit}),prisma.changeRequest.count({where})]);return NextResponse.json({changes,total,page,totalPages:Math.max(1,Math.ceil(total/limit))})}catch(e:any){return NextResponse.json(structuredError(e),{status:e?.message==='FORBIDDEN'?403:401})}}
export async function POST(req:NextRequest){try{let u=await requireUser('change:manage'),body=schema.parse(await req.json()),risk=body.risk||calculateRisk(body.type,body.implementationPlan,body.rollbackPlan);if(['HIGH','CRITICAL'].includes(risk)&&!body.rollbackPlan)return NextResponse.json({error:{code:'ROLLBACK_REQUIRED',message:'Rollback plan is mandatory for high or critical changes'}},{status:400});let freezeDetected=detectFreezePeriod(body.windowStart,body.windowEnd),last=await prisma.changeRequest.count({where:{tenantId:u.tenantId}}),id=`CHG-${String(last+1).padStart(4,'0')}`,change=await prisma.$transaction(async tx=>{let created=await tx.changeRequest.create({data:{title:body.title,description:body.description,type:body.type,status:body.type==='NORMAL'?'CAB_REVIEW':initialStatusForType(body.type),risk,implementationPlan:body.implementationPlan,rollbackPlan:body.rollbackPlan,windowStart:body.windowStart,windowEnd:body.windowEnd,id,tenantId:u.tenantId,requesterId:u.id,approvals:{create:body.approvers.map(a=>({...a,status:body.type==='STANDARD'?'APPROVED':'PENDING',decidedAt:body.type==='STANDARD'?new Date():undefined}))}}});await tx.auditLog.create({data:{tenantId:u.tenantId,userId:u.id,action:'CREATE',entityType:'Change',entityId:id,newValue:{title:body.title,type:body.type,risk,freezeDetected}}});return created});return NextResponse.json({...change,freezeDetected},{status:201})}catch(e){let m=e instanceof Error?e.message:'INVALID_REQUEST';return NextResponse.json(structuredError(e),{status:m==='FORBIDDEN'?403:400})}}
