'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';

const jsonHeaders={'content-type':'application/json','x-requested-with':'XMLHttpRequest'};

export function TicketDetail({initial}:{initial:any}){
  let[t,setT]=useState(initial),[text,setText]=useState(''),[internal,setInternal]=useState(false),r=useRouter();
  async function patch(k:string,v:string){let x=await fetch(`/api/tickets/${t.id}`,{method:'PATCH',headers:jsonHeaders,body:JSON.stringify({[k]:v})});if(x.ok)setT({...t,[k]:v})}
  async function reply(e:React.FormEvent){e.preventDefault();let x=await fetch(`/api/tickets/${t.id}/comments`,{method:'POST',headers:jsonHeaders,body:JSON.stringify({content:text,isInternal:internal})});if(x.ok){let c=await x.json();setT({...t,comments:[...t.comments,c]});setText('')}}
  let next=t.allowedTransitions||['OPEN','IN_PROGRESS','PENDING_CUSTOMER','ON_HOLD','RESOLVED','CLOSED'];
  return <><div className="mb-6 flex flex-wrap items-center gap-3"><button onClick={()=>r.back()}>Back</button><span className="font-mono font-bold text-blue-700">#{t.id}</span><h1 className="text-2xl font-bold">{t.title}</h1><span className="badge bg-blue-100 text-blue-800">{t.status}</span></div><div className="grid gap-5 lg:grid-cols-3"><section className="lg:col-span-2"><div className="card"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-blue-100 font-bold text-blue-700">{t.requester.name.split(' ').map((x:string)=>x[0]).join('')}</div><div><b>{t.requester.name}</b><p className="text-xs text-slate-500">{new Date(t.createdAt).toLocaleString()}</p></div></div><p className="mt-5 whitespace-pre-wrap leading-7">{t.description}</p></div><h3 className="my-4 font-bold">Conversation</h3>{t.comments.map((c:any)=><div key={c.id} className={`card mb-3 ${c.isInternal?'border-amber-300 bg-amber-50':''}`}><b>{c.isInternal?'Internal note - ':''}{c.author.name}</b><p className="mt-2">{c.content}</p></div>)}<form onSubmit={reply} className="card mt-4"><textarea className="input min-h-28" required value={text} onChange={e=>setText(e.target.value)} placeholder="Write a reply..."/><div className="mt-3 flex items-center gap-3"><label><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/> Internal note</label><button className="btn ml-auto">Send reply</button></div></form></section><aside className="card h-fit"><h3 className="mb-4 font-bold">Properties</h3>{['PENDING_CUSTOMER','ON_HOLD'].includes(t.status)&&<p className="mb-3 rounded bg-amber-100 p-2 text-sm font-semibold">SLA on hold</p>}<label className="text-sm font-semibold">Status</label><select className="input mb-4 mt-1" value={t.status} onChange={e=>patch('status',e.target.value)}><option>{t.status}</option>{next.map((x:string)=><option key={x}>{x}</option>)}</select><label className="text-sm font-semibold">Priority</label><select className="input mb-4 mt-1" value={t.priority} onChange={e=>patch('priority',e.target.value)}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select><div className="border-t pt-4 text-sm"><p><b>Requester:</b> {t.requester.name}</p><p><b>Assignee:</b> {t.assignee?.name||'Unassigned'}</p><p><b>Category:</b> {t.category}</p><p><b>Due:</b> {t.dueDate?new Date(t.dueDate).toLocaleString():'-'}</p><p><b>SLA:</b> {t.slaStatus}</p><p><b>Business remaining:</b> {t.businessTimeRemaining||'Calculated by worker'}</p></div></aside></div></>
}
