import type {NextAuthOptions} from 'next-auth';
import {randomUUID} from 'crypto';
import Credentials from 'next-auth/providers/credentials';
import bcrypt from 'bcryptjs';
import {prisma} from './prisma';
import {clearLoginAttempts,consumeLoginAttempt} from './rate-limit';
import {createAccessToken} from './auth/tokens';
import {createRefreshToken,accessCookieName,refreshCookieName} from './auth/refresh-token';
import {demoUser,isLocalDemo} from './demo-data';
function localDemoUser(username:string,password?:string){if(!isLocalDemo()||username!=='admin'||password!=='admin123')return null;return demoUser as any}
export const authOptions:NextAuthOptions={session:{strategy:'jwt',maxAge:30*60},pages:{signIn:'/login'},providers:[Credentials({name:'Credentials',credentials:{username:{label:'Username',type:'text'},password:{label:'Password',type:'password'}},async authorize(c,req){let username=c?.username?.trim().toLowerCase()||'',ip=String(req.headers?.['x-forwarded-for']||req.headers?.['x-real-ip']||'unknown').split(',')[0].trim(),userAgent=String(req.headers?.['user-agent']||'unknown'),key=`${ip}:${username}`,rate=await consumeLoginAttempt(key);if(!rate.allowed)throw new Error(`RATE_LIMITED:${rate.retryAfter}`);let demo=localDemoUser(username,c?.password);if(demo){await clearLoginAttempts(key);return demo}try{let user=username?await prisma.user.findUnique({where:{username}}):null,success=!!(user?.isActive&&user.tenantId&&c?.password&&await bcrypt.compare(c.password,user.password));await prisma.loginEvent.create({data:{tenantId:user?.tenantId,userId:user?.id,username,success,reason:success?null:user?.isActive===false?'INACTIVE':'INVALID_CREDENTIALS',ipAddress:ip,userAgent}}).catch(()=>undefined);if(!success)return null;await clearLoginAttempts(key);return{id:user!.id,name:user!.name,email:user!.email,role:user!.role,tenantId:user!.tenantId} as any}catch{return null}}})],callbacks:{async jwt({token,user}){if(user){token.id=user.id;token.role=(user as any).role;token.tenantId=(user as any).tenantId;token.csrfToken=randomUUID();token.accessToken=createAccessToken(user as any);if(!isLocalDemo())try{let refresh=await createRefreshToken({id:user.id,tenantId:(user as any).tenantId},'nextauth');token.refreshToken=refresh.token}catch{}}return token},async session({session,token}){if(session.user){(session.user as any).id=token.id;(session.user as any).role=token.role;(session.user as any).tenantId=token.tenantId;(session.user as any).csrfToken=token.csrfToken;(session as any).accessToken=token.accessToken;(session as any)[refreshCookieName]=token.refreshToken;(session as any)[accessCookieName]=token.accessToken}return session}}};
