import {NextRequest,NextResponse} from 'next/server';
import {Prisma} from '@prisma/client';
import {z} from 'zod';
import {prisma} from '@/lib/prisma';
import {requireUser} from '@/lib/session';
import {sanitizeHtml} from '@/lib/sanitize';
import {structuredError} from '@/lib/api-errors';
import {shouldSuggestProblem,normalizeFiveWhys} from '@/lib/problem-management';

const schema=z.object({title:z.string().min(4),description:z.string().min(10).transform(sanitizeHtml),ownerId:z.string(),status:z.enum(['INVESTIGATING','IDENTIFIED','MITIGATED','CLOSED']).default('INVESTIGATING'),rootCause:z.string().optional().transform(x=>x?sanitizeHtml(x):x),symptoms:z.string().optional().transform(x=>x?sanitizeHtml(x):x),contributingFactors:z.array(z.string()).default([]),workaround:z.string().optional().transform(x=>x?sanitizeHtml(x):x),fiveWhys:z.array(z.string()).default([]),isKnownError:z.boolean().default(false),kbArticleId:z.string().nullable().optional(),ticketIds:z.array(z.string()).default([]),resolveLinkedIncidents:z.boolean().default(false)});
export async function GET(){let u=await requireUser('problem:manage'),[problems,groups]=await Promise.all([prisma.problem.findMany({where:{tenantId:u.tenantId},include:{owner:{select:{name:true}},_count:{select:{incidents:true}}},orderBy:{updatedAt:'desc'}}),prisma.ticket.groupBy({by:['category','subcategory'],where:{tenantId:u.tenantId,deletedAt:null},_count:{_all:true},having:{id:{_count:{gte:5}}} as any}).catch(()=>[])]);return NextResponse.json({problems,total:problems.length,suggestions:(groups as any[]).filter(g=>shouldSuggestProblem(g._count?._all||0))})}
export async function POST(req:NextRequest){try{let u=await requireUser('problem:manage'),{ticketIds,resolveLinkedIncidents,...data}=schema.parse(await req.json()),valid=await prisma.ticket.findMany({where:{tenantId:u.tenantId,id:{in:ticketIds}},select:{id:true}}),count=await prisma.problem.count({where:{tenantId:u.tenantId}}),id=`PRB-${String(count+1).padStart(4,'0')}`,problem=await prisma.$transaction(async tx=>{let created=await tx.problem.create({data:{...data,id,tenantId:u.tenantId,contributingFactors:data.contributingFactors as Prisma.InputJsonArray,fiveWhys:normalizeFiveWhys(data.fiveWhys) as Prisma.InputJsonArray,incidents:{create:valid.map(t=>({ticketId:t.id}))}}});if(data.status==='CLOSED'&&resolveLinkedIncidents&&valid.length)await tx.ticket.updateMany({where:{tenantId:u.tenantId,id:{in:valid.map(t=>t.id)},status:{notIn:['CLOSED','RESOLVED']}},data:{status:'RESOLVED',resolvedAt:new Date()}});await tx.auditLog.create({data:{tenantId:u.tenantId,userId:u.id,action:'CREATE',entityType:'Problem',entityId:id,newValue:{title:data.title,linkedIncidents:valid.length,isKnownError:data.isKnownError}}});return created});return NextResponse.json(problem,{status:201})}catch(e){let m=e instanceof Error?e.message:'INVALID_REQUEST';return NextResponse.json(structuredError(e),{status:m==='FORBIDDEN'?403:400})}}
